export const STORAGE_KEY = "titleflow.files.v3";
export const TEMPLATE_STORAGE_KEY = "titleflow.templates.v1";

export const workspaceTabs = [
  "Overview",
  "Property",
  "Contacts",
  "Loan",
  "Payoffs",
  "Documents",
  "Checklist",
  "Emails",
  "Notes",
  "Title Commitment",
];

export const contactRoles = [
  "Buyer",
  "Seller",
  "Listing Agent",
  "Buyer's Agent",
  "Lender",
  "Loan Officer",
  "Processor",
  "Insurance Contact",
  "HOA Contact",
  "Payoff Contact",
  "Other",
];

export const documentFolders = ["Title", "Closing", "Loan", "Payoffs", "Property", "Entity Docs", "Recording", "Other"];

export const documentTemplate = [
  "PR",
  "CPL",
  "wire instructions",
  "articles",
  "operating agreement",
  "deed of trust",
  "settlement statement",
  "plat map",
  "tax certificate",
  "insurance invoice",
];

export const mergeFields = [
  "{{fileNumber}}",
  "{{borrower}}",
  "{{seller}}",
  "{{propertyAddress}}",
  "{{county}}",
  "{{purchasePrice}}",
  "{{loanAmount}}",
  "{{lender}}",
  "{{closingDate}}",
  "{{loanNumber}}",
  "{{vesting}}",
  "{{legalDescription}}",
  "{{taxParcel}}",
  "{{todayDate}}",
];

export const templateTypes = [
  "Email Template",
  "Document Template",
  "Title Commitment Template",
  "Checklist Template",
];

export const sampleTemplates = [
  {
    id: 1,
    name: "Payoff Request",
    type: "Email Template",
    description: "Requests a payoff statement from the current payoff contact or lender.",
    body:
      "Subject: Payoff Request - {{fileNumber}} - {{borrower}}\n\nHello,\n\nPlease provide an updated payoff statement for {{borrower}} related to {{propertyAddress}}. Please include the good-through date, per diem, wire instructions, release requirements, and any fees needed for closing.\n\nFile: {{fileNumber}}\nClosing date: {{closingDate}}\n\nThank you,\nTitleFlow Team",
  },
  {
    id: 2,
    name: "Lender Package Request",
    type: "Email Template",
    description: "Requests final lender requirements and closing package items.",
    body:
      "Subject: Lender Package Request - {{fileNumber}}\n\nHello {{lender}},\n\nWe are preparing title and escrow for {{borrower}} at {{propertyAddress}}. Please send final closing instructions, mortgagee clause confirmation, funding conditions, and any required endorsements.\n\nLoan number: {{loanNumber}}\nLoan amount: {{loanAmount}}\nClosing date: {{closingDate}}\n\nBest,\nTitleFlow Team",
  },
  {
    id: 3,
    name: "Missing Documents Request",
    type: "Email Template",
    description: "Follow-up template for missing file documents.",
    body:
      "Subject: Missing Documents - {{fileNumber}}\n\nHello,\n\nWe are finalizing {{fileNumber}} for {{propertyAddress}}. Please send the remaining requested documents so we can keep the closing on schedule.\n\nBorrower: {{borrower}}\nSeller: {{seller}}\n\nThank you,\nTitleFlow Team",
  },
  {
    id: 4,
    name: "HOA Assessment Request",
    type: "Email Template",
    description: "Requests HOA, assessment, transfer, and demand details.",
    body:
      "Subject: HOA / Assessment Request - {{fileNumber}}\n\nHello,\n\nPlease provide current HOA, assessment, transfer, resale, and demand information for {{propertyAddress}} in {{county}} County. We are preparing settlement for {{borrower}} with an expected closing date of {{closingDate}}.\n\nThank you,\nTitleFlow Team",
  },
  {
    id: 5,
    name: "Basic Title Commitment Summary",
    type: "Title Commitment Template",
    description: "A clean commitment summary using the active file data.",
    body:
      "TITLEFLOW TITLE COMMITMENT SUMMARY\n\nFile: {{fileNumber}}\nProperty: {{propertyAddress}}\nCounty: {{county}}\nPurchase Price: {{purchasePrice}}\nLoan Amount: {{loanAmount}}\nProposed Insured / Lender: {{lender}}\nVesting: {{vesting}}\nTax Parcel: {{taxParcel}}\n\nLegal Description:\n{{legalDescription}}\n\nPrepared: {{todayDate}}",
  },
];

function createDocumentList(completedNames) {
  const completed = new Set(completedNames.map((name) => name.toLowerCase()));
  return documentTemplate.map((name) => ({
    id: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    name,
    complete: completed.has(name.toLowerCase()),
    notes: "",
  }));
}

export const sampleFiles = [
  {
    id: 1,
    fileNumber: "1-2026",
    borrower: "Maya Bennett",
    seller: "Jordan Ellis",
    purchasePrice: 0,
    closingDate: "2026-05-08",
    status: "Clear to close",
    progress: 82,
    transactionType: "refinance",
    entityType: "individual",
    isConstruction: false,
    property: {
      address: "1840 Willow Ridge Dr",
      city: "Denver",
      state: "CO",
      zip: "80209",
      county: "Denver",
      parcelId: "05283-18-014",
      legalDescription: "Lot 14, Block 3, Willow Ridge Filing No. 2",
      vesting: "Maya Bennett, an unmarried person",
      occupancyType: "Primary residence",
    },
    loan: {
      lender: "Summit Trust Bank",
      loanNumber: "STB-884102",
      loanAmount: 548000,
      loanType: "Conventional refinance",
      mortgageeClause: "Summit Trust Bank ISAOA ATIMA, PO Box 1840, Denver, CO 80202",
      loanOfficer: "Theo Park",
      processor: "Iris Lee",
      closingDate: "2026-05-08",
    },
    payoff: {
      lender: "Front Range Servicing",
      phone: "(303) 555-0180",
      email: "payoffs@frservicing.example",
      accountNumber: "FR-5500182",
      orderedStatus: "ordered",
      goodThroughDate: "2026-05-10",
      amount: 431225,
      notes: "Need updated payoff letter with per diem before final CD.",
    },
    contacts: [
      {
        id: 101,
        role: "Buyer",
        name: "Maya Bennett",
        company: "Self",
        email: "maya@example.com",
        phone: "(303) 555-0184",
        notes: "Prefers email updates after 2 PM.",
      },
      {
        id: 102,
        role: "Loan Officer",
        name: "Theo Park",
        company: "Summit Trust Bank",
        email: "theo.park@summit.example",
        phone: "(720) 555-0149",
        notes: "Needs final CD one business day before signing.",
      },
      {
        id: 103,
        role: "Insurance Contact",
        name: "Kim Wallace",
        company: "Shield Home Insurance",
        email: "kwallace@shield.example",
        phone: "(303) 555-0128",
        notes: "Binder pending lender mortgagee clause.",
      },
    ],
    documents: createDocumentList(["PR", "CPL", "wire instructions", "settlement statement"]),
    uploadedDocuments: [
      {
        id: 1001,
        name: "Summit closing instructions.pdf",
        folder: "Loan",
        uploadDate: "2026-04-26T15:14:00.000Z",
        size: 248900,
        type: "application/pdf",
        contentBase64: "",
      },
    ],
    checklistCompletions: {
      "Order current payoff statement": true,
      "Confirm vesting and borrower identity": true,
      "Verify lender closing instructions": true,
    },
    emailDraft: null,
    titleCommitment: {},
    notes: "Borrower requested mobile notary if signing after 4 PM. Confirm final hazard binder before funding.",
  },
  {
    id: 2,
    fileNumber: "2-2026",
    borrower: "Northline Holdings LLC",
    seller: "Rivergate Partners",
    purchasePrice: 875000,
    closingDate: "2026-05-15",
    status: "Docs outstanding",
    progress: 56,
    transactionType: "purchase",
    entityType: "LLC",
    isConstruction: false,
    property: {
      address: "91 Harbor Walk",
      city: "Tampa",
      state: "FL",
      zip: "33602",
      county: "Hillsborough",
      parcelId: "A-19-29-18-4Z4-000016-00002.0",
      legalDescription: "Unit 2, Harbor Walk Commercial Condominium",
      vesting: "Northline Holdings LLC, a Florida limited liability company",
      occupancyType: "Investment",
    },
    loan: {
      lender: "Civic Capital",
      loanNumber: "CC-720144",
      loanAmount: 720000,
      loanType: "Commercial purchase",
      mortgageeClause: "Civic Capital LLC ISAOA ATIMA, 410 Market St, Tampa, FL 33602",
      loanOfficer: "Jules Morton",
      processor: "Malik Stone",
      closingDate: "2026-05-15",
    },
    payoff: {
      lender: "Rivergate Partners",
      phone: "(813) 555-0134",
      email: "accounting@rivergate.example",
      accountNumber: "Seller payoff pending",
      orderedStatus: "not ordered",
      goodThroughDate: "",
      amount: 0,
      notes: "Seller says no institutional payoff. Confirm assessment balance.",
    },
    contacts: [
      {
        id: 201,
        role: "Buyer",
        name: "Nora Li",
        company: "Northline Holdings LLC",
        email: "nora@northline.example",
        phone: "(813) 555-0198",
        notes: "Authorized signer for closing documents.",
      },
      {
        id: 202,
        role: "Processor",
        name: "Malik Stone",
        company: "Civic Capital",
        email: "malik.stone@civic.example",
        phone: "(813) 555-0171",
        notes: "Entity approval package due by Friday.",
      },
      {
        id: 203,
        role: "Listing Agent",
        name: "Parker Rose",
        company: "Bayfront Realty",
        email: "prose@bayfront.example",
        phone: "(813) 555-0155",
        notes: "Coordinates seller-side access and walkthrough.",
      },
    ],
    documents: createDocumentList(["PR", "tax certificate", "articles"]),
    uploadedDocuments: [
      {
        id: 2001,
        name: "Northline articles.pdf",
        folder: "Entity Docs",
        uploadDate: "2026-04-25T17:40:00.000Z",
        size: 182420,
        type: "application/pdf",
        contentBase64: "",
      },
    ],
    checklistCompletions: {
      "Open escrow and confirm purchase contract terms": true,
      "Verify lender closing instructions": true,
    },
    emailDraft: null,
    titleCommitment: {},
    notes: "Entity docs are the main blocker. Buyer expects updated operating agreement from counsel.",
  },
  {
    id: 3,
    fileNumber: "3-2026",
    borrower: "Elliot Harper",
    seller: "Harper Family Trust",
    purchasePrice: 0,
    closingDate: "2026-05-21",
    status: "Title review",
    progress: 34,
    transactionType: "construction",
    entityType: "trust",
    isConstruction: true,
    property: {
      address: "402 Mesa Verde Ln",
      city: "Scottsdale",
      state: "AZ",
      zip: "85251",
      county: "Maricopa",
      parcelId: "173-54-119",
      legalDescription: "Lot 119, Mesa Verde Townhomes, according to Book 418 of Maps",
      vesting: "Elliot Harper, Trustee of the Harper Family Trust dated March 4, 2018",
      occupancyType: "Second home",
    },
    loan: {
      lender: "Apex Home Lending",
      loanNumber: "AHL-39854",
      loanAmount: 398500,
      loanType: "Construction refinance",
      mortgageeClause: "Apex Home Lending ISAOA, 2220 Camelback Rd, Phoenix, AZ 85016",
      loanOfficer: "Riley Cho",
      processor: "Sam Rivera",
      closingDate: "2026-05-21",
    },
    payoff: {
      lender: "Sonoran Mortgage Servicing",
      phone: "(480) 555-0119",
      email: "payoff@sonoran.example",
      accountNumber: "SMS-994018",
      orderedStatus: "received",
      goodThroughDate: "2026-05-22",
      amount: 281440,
      notes: "Includes construction draw holdback instructions.",
    },
    contacts: [
      {
        id: 301,
        role: "Buyer",
        name: "Elliot Harper",
        company: "Self",
        email: "elliot@example.com",
        phone: "(480) 555-0107",
        notes: "Trust documents are with estate attorney.",
      },
      {
        id: 302,
        role: "HOA Contact",
        name: "Sofia Grant",
        company: "Desert Vista HOA",
        email: "sofia@desertvista.example",
        phone: "(480) 555-0132",
        notes: "Demand ordered, rush fee approved.",
      },
    ],
    documents: createDocumentList(["PR", "plat map", "deed of trust"]),
    uploadedDocuments: [
      {
        id: 3001,
        name: "Mesa Verde plat map.png",
        folder: "Property",
        uploadDate: "2026-04-24T21:05:00.000Z",
        size: 925112,
        type: "image/png",
        contentBase64: "",
      },
    ],
    checklistCompletions: {
      "Review construction draw and funding requirements": true,
    },
    emailDraft: null,
    titleCommitment: {},
    notes: "Trust certification and HOA demand are still outstanding. Construction endorsement questions sent to underwriter.",
  },
];
